In [6]:
import os
import pandas as pd
from sqlalchemy import create_engine

In [7]:
data_url = 'https://raw.githubusercontent.com/datasets/population/main/data/population.csv'
df = pd.read_csv(data_url)
print(f"Shape: {df.shape}")
df.head()

Shape: (17195, 4)

  Country Name Country Code  Year  Value
0        Aruba          ABW  1960  54922
1        Aruba          ABW  1961  55578
2        Aruba          ABW  1962  56320
3        Aruba          ABW  1963  57002
4        Aruba          ABW  1964  57619

In [8]:
print(df.dtypes)
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nDuplicates: {df.duplicated().sum()}")

Country Name      str
Country Code      str
Year            int64
Value           int64
dtype: object

Missing values:
Country Name    0
Country Code    0
Year            0
Value           0
dtype: int64

Duplicates: 0

In [9]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df = df.dropna()
df = df.drop_duplicates()
print(f"Clean shape: {df.shape}")
df.head()

Clean shape: (17195, 4)

  country_name country_code  year  value
0        Aruba          ABW  1960  54922
1        Aruba          ABW  1961  55578
2        Aruba          ABW  1962  56320
3        Aruba          ABW  1963  57002
4        Aruba          ABW  1964  57619

In [10]:
engine = create_engine(
    f"postgresql+psycopg2://root:root@localhost:5433/population_db"
)

df.to_sql(
    name='world_population',
    con=engine,
    if_exists='replace',
    index=False
)

count = pd.read_sql("SELECT COUNT(*) FROM world_population", engine).iloc[0, 0]
print(f"Done! {count} rows loaded into world_population")

Done! 17195 rows loaded into world_population